name: Unit Tests Action

description: 'Run unit tests for the specified service'
inputs:
  service:
    description: 'Name of the service to test'
    required: true
  language:
    description: 'Programming language of the service'
    required: true
  working_directory:
    description: 'Directory of the service'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Dependencies
      shell: bash
      run: |
        set -e
        case "${{ inputs.language }}" in
          node)
            npm ci
            ;;
          python)
            if [ -f "${{ inputs.working_directory }}/pyproject.toml" ]; then
              if ! command -v poetry &> /dev/null; then
                curl -sSL https://install.python-poetry.org | python3 -
                export PATH="$HOME/.local/bin:$PATH"
              fi
              poetry install --no-root -C "${{ inputs.working_directory }}"
            else
              echo "No dependency file found for Python in ${{ inputs.working_directory }}"
              exit 1
            fi
            ;;
          java)
            chmod +x gradlew
            ./gradlew build --no-daemon
            ;;
          *)
            echo "Unsupported language: ${{ inputs.language }}"
            exit 1
            ;;
        esac
      working-directory: ${{ inputs.working_directory }}

    - name: Run Unit Tests
      shell: bash
      run: |
        set -e
        case "${{ inputs.language }}" in
          node)
            npm test
            ;;
          python)
            poetry run pytest
            ;;
          java)
            ./gradlew test --no-daemon
            ;;
          *)
            echo "Unsupported language: ${{ inputs.language }}"
            exit 1
            ;;
        esac
      working-directory: ${{ inputs.working_directory }}
