version: 2
updates:
  - package-ecosystem: "npm"
    directory: "frontend"
    schedule:
      interval: "daily"
    target-branch: "develop"
  - package-ecosystem: "npm"
    directory: "activity-tracking"
    schedule:
      interval: "daily"
    target-branch: "develop"
  - package-ecosystem: "pip"
    directory: "analytics"
    schedule:
      interval: "daily"
    target-branch: "develop"
  - package-ecosystem: "pip"
    directory: "recipes"
    schedule:
      interval: "daily"
    target-branch: "develop"
  - package-ecosystem: "gradle"
    directory: "authservice"
    schedule:
      interval: "daily"
    target-branch: "develop"