[tool.poetry]
name = "recipes"
version = "0.1.0"
description = ""
authors = ["diana-create <dianamuse9@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.8"
flask = "2.3.2"
pymongo = "4.6.3"
gunicorn = "^23.0.0"
python-dotenv = "0.19.0"
flask-pymongo = "2.3.0"
flask-cors = "^5.0.0"
ariadne = "0.23.0"
jinja2 = "^3.1.4"
wheel = "^0.45.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
pytest-flask = "^1.3.0"
mongomock = "^4.2.0.post1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
