[tool.poetry]
name = "recipes"
version = "0.1.0"
description = ""
authors = ["diana-create <dianamuse9@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
ariadne = "0.23.0"
flake8-import-order = "^0.18.1"
flask = "2.3.2"
flask-cors = "^5.0.0"
flask-pymongo = "2.3.0"
gunicorn = "^23.0.0"
jinja2 = "^3.1.4"
python = ">=3.8.1,<4.0"
pymongo = "4.6.3"
python-dotenv = "0.19.0"
wheel = "^0.45.0"


[tool.poetry.group.dev.dependencies]
flake8 = "^7.1.1"
flake8-import-order = "^0.18.1"
pytest = "^8.3.3"
mongomock = "^4.2.0.post1"
isort = "^5.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.flake8]
max-line-length = 79
extend-ignore = "E203,W503"
import-order-style = "google"  # Options: 'google', 'pep8', etc.
application-import-names = ["your_project_name"]

[tool.isort] ##  A tool to sort imports automatically
profile = "black"
line_length = 79
multi_line_output = 3