[tool.poetry]
name = "recipes"
version = "0.1.0"
description = ""
authors = ["diana-create <dianamuse9@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
flask = "2.3.2"
flake8 = "^6.0.0"
pytest = "^8.3.3"
pymongo = "4.2.0"
gunicorn = "20.1.0"
python-dotenv = "0.19.0"
flask-pymongo = "2.3.0"
flask-cors = "3.0.10"
ariadne = "0.23.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
