[tool.poetry]
name = "recipes"
version = "0.1.0"
description = ""
authors = ["diana-create <dianamuse9@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
ariadne = "0.23.0"
flask = "2.3.2"
flask-cors = "^5.0.0"
flask-pymongo = "2.3.0"
gunicorn = "^23.0.0"
jinja2 = "^3.1.4"
python = ">=3.8.1,<4.0"
pymongo = "4.6.3"
python-dotenv = "0.19.0"
wheel = "^0.45.0"


[tool.poetry.group.dev.dependencies]
flake8 = "^7.1.1"
pytest = "^8.3.3"
mongomock = "^4.2.0.post1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.flake8]
max-line-length = 79

[tool.isort]
profile = "black"  # Use Black-compatible formatting
line_length = 79