version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/app/build
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  activity-tracking:
    build:
      context: ./activity-tracking
      dockerfile: Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: ${MONGO_URI}
    ports:
      - "5300:5300"
    depends_on:
      - mongodb
    networks:
      - app-network

  analytics:
    build:
      context: ./analytics
      dockerfile: Dockerfile
    environment:
      # SPRING_DATA_MONGODB_DATABASE: SPRING_DATA_MONGODB_DATABASE
      SPRING_DATA_MONGODB_DATABASE: authservice
      MONGO_URI: ${MONGO_URI}
    ports:
      - "5050:5050"
    depends_on:
      - mongodb
    networks:
      - app-network

  recipes:
    build:
      context: ./recipes
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
    ports:
      - "5051:5051"
    depends_on:
      - mongodb
    networks:
      - app-network

  authservice:
    build:
      context: ./authservice
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_MONGODB_DATABASE=${MONGO_DB_AUTH_DATABASE}
      - SPRING_DATA_MONGODB_URI=${MONGO_URI}
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodbdata:
