services:
  nginx: # Nginx acts as the single entry point to your application
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      -  /workspaces/TEAM-3-MLA-app/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - activity-tracking
      - analytics
      - authservice
      - recipes
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - app-network

  activity-tracking:
    build:
      context: ./activity-tracking
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - app-network

  analytics:
    build:
      context: ./analytics
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://root:cfgmla23@mongodb:27017
    ports:
      - "5050:5050"
    depends_on:
      - mongodb
    networks:
      - app-network

  recipes:
    build:
      context: ./recipes
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://root:cfgmla23@mongodb:27017
    ports:
      - "5051:5051"
    depends_on:
      - mongodb
    networks:
      - app-network

  authservice:
    build:
      context: ./authservice
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_MONGODB_DATABASE=test
      - SPRING_DATA_MONGODB_URI=mongodb://root:cfgmla23@mongodb:27017
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=cfgmla23
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodbdata:
