version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
  activity-tracking:
    build:
      context: ./activity-tracking
      dockerfile: Dockerfile
    environment:
      - NODE_ENV
      - MONGO_DB
      - MONGO_URI
    ports:
      - "5300:5300"
    depends_on:
      - mongodb
    networks:
      - app-network

  analytics:
    build:
      context: ./analytics
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV_DEV}
      - MONGO_URI=${MONGO_URI_DEV}
      - MONGO_DB=${MONGO_DB_DEV}
    ports:
      - "5050:5050"
    depends_on:
      - mongodb
    networks:
      - app-network

  authservice:
    build:
      context: ./authservice
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_MONGODB_DATABASE=${SPRING_DATA_MONGODB_DATABASE_DEV}
      - SPRING_DATA_MONGODB_URI=${MONGO_URI_DEV}
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    environment:
    - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodbdata:
