name: Lint Action

description: 'Lint the specified service'
inputs:
  service:
    description: 'Name of the service to lint'
    required: true
  language:
    description: 'Programming language of the service'
    required: true
  working_directory:
    description: 'Directory of the service'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Dependencies
      shell: bash
      run: |
        set -e
        case "${{ inputs.language }}" in
          node)
            npm ci
            ;;
          python)
            pip install --no-cache-dir -r requirements.txt
            ;;
          java)
            chmod +x gradlew
            ./gradlew build --no-daemon
            ;;
          *)
            echo "Unsupported language: ${{ inputs.language }}"
            exit 1
            ;;
        esac
      working-directory: ${{ inputs.working_directory }}

    - name: Run Linter
      shell: bash
      run: |
        set -e
        case "${{ inputs.language }}" in
          node)
            npm run lint
            ;;
          python)
            flake8 .
            ;;
          java)
            ./gradlew checkstyleMain --no-daemon
            ;;
          *)
            echo "Unsupported language: ${{ inputs.language }}"
            exit 1
            ;;
        esac
      working-directory: ${{ inputs.working_directory }}
