# ––––––––––––––––––––––––––––––––
# Alternative to ECR deployment.
# Add DOCKER_USERNAME, DOCKER_PASSWORD and your username to Github secrets
# before attempting to run the pipeline.
# ––––––––––––––––––––––––––––––––

name: Deploy to Docker Hub

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, tag, and push image to Docker Hub (Frontend)
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mla-fitnessapp-fe:latest -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/mla-fitnessapp-fe:latest

      - name: Build, tag, and push image to Docker Hub (Activity Tracking)
        run: |
          cd activity-tracking
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mla-fitnessapp-activity:latest -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/mla-fitnessapp-activity:latest

      - name: Build, tag, and push image to Docker Hub (AuthService)
        run: |
          cd authservice
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mla-fitnessapp-authservice:latest -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/mla-fitnessapp-authservice:latest

      - name: Build, tag, and push image to Docker Hub (Analytics)
        run: |
          cd analytics
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mla-fitnessapp-analytics:latest -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/mla-fitnessapp-analytics:latest
