name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - develop
      - CI-workflow
  pull_request:
    branches:
      - develop
      - CI-workflow
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: false
        default: 'develop'
      services:
        description: 'Comma-separated list of services to build and deploy'
        required: false
      run_lint:
        description: 'Run Lint Job (true/false)'
        required: false
        default: 'true'
      run_unit_tests:
        description: 'Run Unit Tests Job (true/false)'
        required: false
        default: 'true'
      run_build_and_deploy:
        description: 'Run Build and Deploy Job (true/false)'
        required: false
        default: 'true'

jobs:
  lint:
    name: Run Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["frontend", "activity-tracking", "authservice", "analytics", "recipes"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Service Variables
        run: |
          case "${{ matrix.service }}" in
            frontend)
              echo "language=node" >> $GITHUB_ENV
              echo "working_directory=frontend" >> $GITHUB_ENV
              ;;
            activity-tracking)
              echo "language=node" >> $GITHUB_ENV
              echo "working_directory=activity-tracking" >> $GITHUB_ENV
              ;;
            analytics)
              echo "language=python" >> $GITHUB_ENV
              echo "working_directory=analytics" >> $GITHUB_ENV
              ;;
            recipes)
              echo "language=python" >> $GITHUB_ENV
              echo "working_directory=recipes" >> $GITHUB_ENV
              ;;
            authservice)
              echo "language=java" >> $GITHUB_ENV
              echo "working_directory=authservice" >> $GITHUB_ENV
              ;;
            *)
              echo "Unsupported service: $SERVICE"
              exit 1
              ;;
          esac

      # Set up language environments
      - name: Set up Node.js
        if: ${{ env.language == 'node' }}
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ${{ env.working_directory }}/package-lock.json

      - name: Set up Python
        if: ${{ env.language == 'python' }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
          cache-dependency-path: ${{ env.working_directory }}/requirements.txt

      - name: Set up Java
        if: ${{ env.language == 'java' }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      
      - name: Cache Gradle Dependencies
        if: ${{ env.language == 'java' }}
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles(format('{0}/**/*.gradle*', env.working_directory)) }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Lint
        uses: ./.github/actions/lint
        with:
          service: ${{ matrix.service }}
          language: ${{ env.language }}
          working_directory: ${{ env.working_directory }}

  unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["frontend", "activity-tracking", "authservice", "analytics", "recipes"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Service Variables
        run: |
          case "${{ matrix.service }}" in
            frontend)
              echo "language=node" >> $GITHUB_ENV
              echo "working_directory=frontend" >> $GITHUB_ENV
              ;;
            activity-tracking)
              echo "language=node" >> $GITHUB_ENV
              echo "working_directory=activity-tracking" >> $GITHUB_ENV
              ;;
            analytics)
              echo "language=python" >> $GITHUB_ENV
              echo "working_directory=analytics" >> $GITHUB_ENV
              ;;
            recipes)
              echo "language=python" >> $GITHUB_ENV
              echo "working_directory=recipes" >> $GITHUB_ENV
              ;;
            authservice)
              echo "language=java" >> $GITHUB_ENV
              echo "working_directory=authservice" >> $GITHUB_ENV
              ;;
            *)
              echo "Unsupported service: $SERVICE"
              exit 1
              ;;
          esac

      # Set up language environments
      - name: Set up Node.js
        if: ${{ env.language == 'node' }}
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ${{ env.working_directory }}/package-lock.json

      - name: Set up Python
        if: ${{ env.language == 'python' }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: ${{ env.working_directory }}/requirements.txt

      - name: Set up Java
        if: ${{ env.language == 'java' }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      
      - name: Cache Gradle Dependencies
        if: ${{ env.language == 'java' }}
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles(format('{0}/**/*.gradle*', env.working_directory)) }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Unit Tests
        uses: ./.github/actions/unit-tests
        with:
          service: ${{ matrix.service }}
          language: ${{ env.language }}
          working_directory: ${{ env.working_directory }}

  build_and_deploy:
    name: Build and Deploy to Docker Hub
    needs:
      - lint
      - unit_tests
    runs-on: ubuntu-latest
    env:
      NODE_ENV: ${{ secrets.NODE_ENV_DEV }}
      MONGO_DB: ${{ secrets.MONGO_DB_DEV }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      SPRING_DATA_MONGODB_DATABASE: ${{ secrets.SPRING_DATA_MONGODB_DATABASE_DEV }}
      MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
      MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      MONGO_DB_AUTH_DATABASE: authservice-dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          version: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images for All Services
        run: |
          SERVICES=("frontend" "activity-tracking" "authservice" "analytics" "recipes")
          for service in "${SERVICES[@]}"; do
            echo "Building and pushing Docker image for $service"
            docker build -t $DOCKER_USERNAME/$service:latest -f ./$service/Dockerfile ./$service || exit 1
            docker push $DOCKER_USERNAME/$service:latest || exit 1
          done
