name: Frontend Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js using nvm
        shell: bash -l {0}
        run: nvm install

      - name: Install dependencies
        run: npm install
