name: Reusable Unit Testing Workflow

on:
  workflow_call:
    inputs:
      service:
        description: 'Name of the service to test'
        required: true
        type: string
      language:
        description: 'Programming language of the service'
        required: true
        type: string
      working_directory:
        description: 'Directory of the service'
        required: true
        type: string

jobs:
  unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(inputs.services) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Environment for ${{ inputs.language }}
        run: |
          case "${{ inputs.language }}" in
            node)
              # Node.js setup will be handled separately
              ;;
            python)
              sudo apt-get update && sudo apt-get install -y python3-pip
              ;;
            java)
              sudo apt-get update && sudo apt-get install -y openjdk-11-jdk
              ;;
            *)
              echo "Unsupported language: ${{ inputs.language }}"
              exit 1
              ;;
          esac
        working-directory: ${{ inputs.working_directory }}

      - name: Set up Node.js
        if: ${{ inputs.language == 'node' }}
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          case "${{ inputs.language }}" in
            node)
              npm ci
              ;;
            python)
              pip3 install -r requirements.txt
              ;;
            java)
              ./gradlew build --no-daemon
              ;;
          esac
        working-directory: ${{ inputs.working_directory }}

      - name: Run Unit Tests
        run: |
          case "${{ inputs.language }}" in
            node)
              npm test
              ;;
            python)
              pytest || true
              ;;
            java)
              ./gradlew test --no-daemon
              ;;
          esac
        working-directory: ${{ inputs.working_directory }}