name: Reusable Unit Testing Workflow

on:
  workflow_call:
    inputs:
      services:
        description: 'List of services to test'
        required: true
        type: string

jobs:
  unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(inputs.services) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Environment
        run: |
          case "${{ matrix.service }}" in
            frontend | activity-tracking)
              echo "Setting up Node.js"
              actions/setup-node@v3
              node-version: '18'
              ;;
            analytics | recipes)
              echo "Setting up Python"
              sudo apt-get update && sudo apt-get install -y python3-pip
              ;;
            authservice)
              echo "Setting up Java"
              sudo apt-get update && sudo apt-get install -y openjdk-11-jdk
              ;;
            *)
              echo "Unsupported service"
              exit 1
              ;;
          esac
        working-directory: ./${{ matrix.service }}

      - name: Install Dependencies
        run: |
          case "${{ matrix.service }}" in
            frontend | activity-tracking)
              npm ci
              ;;
            analytics | recipes)
              pip3 install -r requirements.txt
              ;;
            authservice)
              ./gradlew build --no-daemon
              ;;
          esac
        working-directory: ./${{ matrix.service }}

      - name: Run Unit Tests
        run: |
          case "${{ matrix.service }}" in
            frontend | activity-tracking)
              npm test
              ;;
            analytics | recipes)
              pytest || true
              ;;
            authservice)
              ./gradlew test --no-daemon
              ;;
          esac
        working-directory: ./${{ matrix.service }}
